//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assesment_SQLQuery8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PDescription { get; set; }
        public decimal PPrice { get; set; }
        public Nullable<System.DateTime> PReleaseDate { get; set; }
    }
}
